"""empty message

Revision ID: 81e9fffaa1a7
Revises: 3114752ba610
Create Date: 2020-01-28 12:02:45.343666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81e9fffaa1a7'
down_revision = '3114752ba610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.Integer(), nullable=False))
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
