"""empty message

Revision ID: d7e9609754a3
Revises: fe00626e6d1e
Create Date: 2020-01-28 10:38:15.339169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e9609754a3'
down_revision = 'fe00626e6d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity',
    sa.Column('item_id', sa.BIGINT(), nullable=False),
    sa.Column('detail_url', sa.String(length=512), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commodity')
    # ### end Alembic commands ###
