"""empty message

Revision ID: dd3833078827
Revises: fbcaaf02d7f7
Create Date: 2020-01-29 15:44:45.840638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd3833078827'
down_revision = 'fbcaaf02d7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_command', sa.Column('status', sa.INTEGER(), nullable=False))
    op.drop_column('admin_command', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_command', sa.Column('create_time', mysql.DATETIME(), nullable=False))
    op.drop_column('admin_command', 'status')
    # ### end Alembic commands ###
